Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Console-Kernel.html"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Aschedule\u0028\u0029",
            "name": "schedule",
            "summary": "Define\u0020the\u0020application\u0027s\u0020command\u0020schedule.",
            "url": "classes/App-Console-Kernel.html#method_schedule"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Acommands\u0028\u0029",
            "name": "commands",
            "summary": "Register\u0020the\u0020commands\u0020for\u0020the\u0020application.",
            "url": "classes/App-Console-Kernel.html#method_commands"
        },                {
            "fqsen": "\\App\\Enums\\EstadoCompraEnum",
            "name": "EstadoCompraEnum",
            "summary": "",
            "url": "classes/App-Enums-EstadoCompraEnum.html"
        },                {
            "fqsen": "\\App\\Enums\\EstadoCompraEnum\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "",
            "url": "classes/App-Enums-EstadoCompraEnum.html#method_getNombre"
        },                {
            "fqsen": "\\App\\Enums\\EstadoCompraEnum\u003A\u003AACTIVO",
            "name": "ACTIVO",
            "summary": "",
            "url": "classes/App-Enums-EstadoCompraEnum.html#constant_ACTIVO"
        },                {
            "fqsen": "\\App\\Enums\\EstadoCompraEnum\u003A\u003ACERRADO",
            "name": "CERRADO",
            "summary": "",
            "url": "classes/App-Enums-EstadoCompraEnum.html#constant_CERRADO"
        },                {
            "fqsen": "\\App\\Enums\\EstadoCompraEnum\u003A\u003AANULADO",
            "name": "ANULADO",
            "summary": "",
            "url": "classes/App-Enums-EstadoCompraEnum.html#constant_ANULADO"
        },                {
            "fqsen": "\\App\\Enums\\EstadoODAEnum",
            "name": "EstadoODAEnum",
            "summary": "",
            "url": "classes/App-Enums-EstadoODAEnum.html"
        },                {
            "fqsen": "\\App\\Enums\\EstadoODAEnum\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "",
            "url": "classes/App-Enums-EstadoODAEnum.html#method_getNombre"
        },                {
            "fqsen": "\\App\\Enums\\EstadoODAEnum\u003A\u003AACTIVO",
            "name": "ACTIVO",
            "summary": "",
            "url": "classes/App-Enums-EstadoODAEnum.html#constant_ACTIVO"
        },                {
            "fqsen": "\\App\\Enums\\EstadoODAEnum\u003A\u003AENATENCION",
            "name": "ENATENCION",
            "summary": "",
            "url": "classes/App-Enums-EstadoODAEnum.html#constant_ENATENCION"
        },                {
            "fqsen": "\\App\\Enums\\EstadoODAEnum\u003A\u003ACERRADO",
            "name": "CERRADO",
            "summary": "",
            "url": "classes/App-Enums-EstadoODAEnum.html#constant_CERRADO"
        },                {
            "fqsen": "\\App\\Enums\\EstadoODAEnum\u003A\u003ANOATENDIDO",
            "name": "NOATENDIDO",
            "summary": "",
            "url": "classes/App-Enums-EstadoODAEnum.html#constant_NOATENDIDO"
        },                {
            "fqsen": "\\App\\Enums\\TipoDocumentoCompraEnum",
            "name": "TipoDocumentoCompraEnum",
            "summary": "",
            "url": "classes/App-Enums-TipoDocumentoCompraEnum.html"
        },                {
            "fqsen": "\\App\\Enums\\TipoDocumentoCompraEnum\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "",
            "url": "classes/App-Enums-TipoDocumentoCompraEnum.html#method_getNombre"
        },                {
            "fqsen": "\\App\\Enums\\TipoDocumentoCompraEnum\u003A\u003AFACTURA",
            "name": "FACTURA",
            "summary": "",
            "url": "classes/App-Enums-TipoDocumentoCompraEnum.html#constant_FACTURA"
        },                {
            "fqsen": "\\App\\Enums\\TipoDocumentoCompraEnum\u003A\u003ANOTAVENTA",
            "name": "NOTAVENTA",
            "summary": "",
            "url": "classes/App-Enums-TipoDocumentoCompraEnum.html#constant_NOTAVENTA"
        },                {
            "fqsen": "\\App\\Enums\\TipoDocumentoCompraEnum\u003A\u003ALIQUIDACIONCOMPRA",
            "name": "LIQUIDACIONCOMPRA",
            "summary": "",
            "url": "classes/App-Enums-TipoDocumentoCompraEnum.html#constant_LIQUIDACIONCOMPRA"
        },                {
            "fqsen": "\\App\\Enums\\TipoRolEnum",
            "name": "TipoRolEnum",
            "summary": "",
            "url": "classes/App-Enums-TipoRolEnum.html"
        },                {
            "fqsen": "\\App\\Enums\\TipoRolEnum\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "",
            "url": "classes/App-Enums-TipoRolEnum.html#method_getNombre"
        },                {
            "fqsen": "\\App\\Enums\\TipoRolEnum\u003A\u003AVISITANTE",
            "name": "VISITANTE",
            "summary": "",
            "url": "classes/App-Enums-TipoRolEnum.html#constant_VISITANTE"
        },                {
            "fqsen": "\\App\\Enums\\TipoRolEnum\u003A\u003AADMINISTRADOR",
            "name": "ADMINISTRADOR",
            "summary": "",
            "url": "classes/App-Enums-TipoRolEnum.html#constant_ADMINISTRADOR"
        },                {
            "fqsen": "\\App\\Enums\\TipoRolEnum\u003A\u003AGERENTE",
            "name": "GERENTE",
            "summary": "",
            "url": "classes/App-Enums-TipoRolEnum.html#constant_GERENTE"
        },                {
            "fqsen": "\\App\\Enums\\TipoRolEnum\u003A\u003AMECANICO",
            "name": "MECANICO",
            "summary": "",
            "url": "classes/App-Enums-TipoRolEnum.html#constant_MECANICO"
        },                {
            "fqsen": "\\App\\Enums\\TipoRolEnum\u003A\u003AVENDEDOR",
            "name": "VENDEDOR",
            "summary": "",
            "url": "classes/App-Enums-TipoRolEnum.html#constant_VENDEDOR"
        },                {
            "fqsen": "\\App\\Enums\\TipoSujetoEnum",
            "name": "TipoSujetoEnum",
            "summary": "",
            "url": "classes/App-Enums-TipoSujetoEnum.html"
        },                {
            "fqsen": "\\App\\Enums\\TipoSujetoEnum\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "",
            "url": "classes/App-Enums-TipoSujetoEnum.html#method_getNombre"
        },                {
            "fqsen": "\\App\\Enums\\TipoSujetoEnum\u003A\u003ACLIENTE",
            "name": "CLIENTE",
            "summary": "",
            "url": "classes/App-Enums-TipoSujetoEnum.html#constant_CLIENTE"
        },                {
            "fqsen": "\\App\\Enums\\TipoSujetoEnum\u003A\u003APROVEEDOR",
            "name": "PROVEEDOR",
            "summary": "",
            "url": "classes/App-Enums-TipoSujetoEnum.html#constant_PROVEEDOR"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "classes/App-Exceptions-Handler.html"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020the\u0020exception\u0020handling\u0020callbacks\u0020for\u0020the\u0020application.",
            "url": "classes/App-Exceptions-Handler.html#method_register"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontReport",
            "name": "dontReport",
            "summary": "A\u0020list\u0020of\u0020the\u0020exception\u0020types\u0020that\u0020are\u0020not\u0020reported.",
            "url": "classes/App-Exceptions-Handler.html#property_dontReport"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontFlash",
            "name": "dontFlash",
            "summary": "A\u0020list\u0020of\u0020the\u0020inputs\u0020that\u0020are\u0020never\u0020flashed\u0020for\u0020validation\u0020exceptions.",
            "url": "classes/App-Exceptions-Handler.html#property_dontFlash"
        },                {
            "fqsen": "\\App\\Exceptions\\Notificacion",
            "name": "Notificacion",
            "summary": "",
            "url": "classes/App-Exceptions-Notificacion.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController",
            "name": "CategoriaController",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoriaController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Devuelve\u0020una\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020una\u0020categoria.",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020en\u0020Base\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020en\u0020Base\u0020de\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003Adel\u0028\u0029",
            "name": "del",
            "summary": "Muestra\u0020el\u0020formulario\u0020modal\u0020para\u0020eliminar\u0020una\u0020categoria.",
            "url": "classes/App-Http-Controllers-CategoriaController.html#method_del"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CategoriaController\u003A\u003A\u0024CategoriaModel",
            "name": "CategoriaModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-CategoriaController.html#property_CategoriaModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController",
            "name": "ClienteController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AgetByDNI\u0028\u0029",
            "name": "getByDNI",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_getByDNI"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003A\u0024ClienteModel",
            "name": "ClienteModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClienteController.html#property_ClienteModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController",
            "name": "CompraController",
            "summary": "",
            "url": "classes/App-Http-Controllers-CompraController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020resource.",
            "url": "classes/App-Http-Controllers-CompraController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-CompraController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-CompraController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-CompraController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-CompraController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-CompraController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompraController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-CompraController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController",
            "name": "EmpresaController",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Almacena\u0020la\u0020categor\u00EDa\u0020reci\u00E9n\u0020creada\u0020en\u0020el\u0020almacenamiento.",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpresaController\u003A\u003A\u0024EmpresaModel",
            "name": "EmpresaModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-EmpresaController.html#property_EmpresaModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController",
            "name": "LoginController",
            "summary": "",
            "url": "classes/App-Http-Controllers-LoginController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Http-Controllers-LoginController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController\u003A\u003Acheck_login\u0028\u0029",
            "name": "check_login",
            "summary": "",
            "url": "classes/App-Http-Controllers-LoginController.html#method_check_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/App-Http-Controllers-LoginController.html#method_logout"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrdenesAtencionController",
            "name": "OrdenesAtencionController",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrdenesAtencionController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrdenesAtencionController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrdenesAtencionController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrdenesAtencionController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrdenesAtencionController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrdenesAtencionController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrdenesAtencionController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrdenesAtencionController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrdenesAtencionController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\OrdenesAtencionController\u003A\u003A\u0024OrdenAtencionModel",
            "name": "OrdenAtencionModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-OrdenesAtencionController.html#property_OrdenAtencionModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController",
            "name": "ProductoController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ProductoController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-ProductoController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020vista\u0020de\u0020todos\u0020los\u0020productos.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Mostrar\u0020el\u0020formulario\u0020para\u0020crear\u0020un\u0020nuevo\u0020producto.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Almacena\u0020el\u0020producto\u0020reci\u00E9n\u0020creada\u0020en\u0020el\u0020almacenamiento.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Devuelve\u0020un\u0020producto.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020un\u0020producto.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020en\u0020Base\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020producto.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020en\u0020Base\u0020de\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020producto.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003Adel\u0028\u0029",
            "name": "del",
            "summary": "Muestra\u0020el\u0020formulario\u0020modal\u0020para\u0020eliminar\u0020un\u0020producto.",
            "url": "classes/App-Http-Controllers-ProductoController.html#method_del"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProductoController\u003A\u003A\u0024ProductoModel",
            "name": "ProductoModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-ProductoController.html#property_ProductoModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController",
            "name": "ProveedorController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ProveedorController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020vista\u0020de\u0020todas\u0020las\u0020categorias.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Mostrar\u0020el\u0020formulario\u0020para\u0020crear\u0020una\u0020nueva\u0020categoria.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Almacena\u0020la\u0020categor\u00EDa\u0020reci\u00E9n\u0020creada\u0020en\u0020el\u0020almacenamiento.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Devuelve\u0020una\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020una\u0020categoria.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020en\u0020Base\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020en\u0020Base\u0020de\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003Adel\u0028\u0029",
            "name": "del",
            "summary": "Muestra\u0020el\u0020formulario\u0020modal\u0020para\u0020eliminar\u0020una\u0020categoria.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_del"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003AgetByDNI\u0028\u0029",
            "name": "getByDNI",
            "summary": "Funci\u00F3n\u0020que\u0020busca\u0020a\u0020un\u0020proveedor\u0020por\u0020el\u0020DNI.",
            "url": "classes/App-Http-Controllers-ProveedorController.html#method_getByDNI"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProveedorController\u003A\u003A\u0024ProveedorModel",
            "name": "ProveedorModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-ProveedorController.html#property_ProveedorModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController",
            "name": "ReportesController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ReportesController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003AshowReport\u0028\u0029",
            "name": "showReport",
            "summary": "",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_showReport"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003ArptNuevosClientes\u0028\u0029",
            "name": "rptNuevosClientes",
            "summary": "",
            "url": "classes/App-Http-Controllers-ReportesController.html#method_rptNuevosClientes"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ReportesController\u003A\u003A\u0024EmpresaModel",
            "name": "EmpresaModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-ReportesController.html#property_EmpresaModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController",
            "name": "TipoServicioController",
            "summary": "",
            "url": "classes/App-Http-Controllers-TipoServicioController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020vista\u0020de\u0020todas\u0020las\u0020categorias.",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Mostrar\u0020el\u0020formulario\u0020para\u0020crear\u0020una\u0020nueva\u0020categoria.",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Almacena\u0020la\u0020categor\u00EDa\u0020reci\u00E9n\u0020creada\u0020en\u0020el\u0020almacenamiento.",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Devuelve\u0020una\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020una\u0020categoria.",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020en\u0020Base\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020en\u0020Base\u0020de\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020categor\u00EDa.",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TipoServicioController\u003A\u003A\u0024TipoServicioModel",
            "name": "TipoServicioModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-TipoServicioController.html#property_TipoServicioModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController",
            "name": "UsuarioController",
            "summary": "",
            "url": "classes/App-Http-Controllers-UsuarioController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020vista\u0020de\u0020todas\u0020las\u0020categorias.",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Mostrar\u0020el\u0020formulario\u0020para\u0020crear\u0020una\u0020nueva\u0020categoria.",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Almacena\u0020la\u0020usuario\n\u0020reci\u00E9n\u0020creada\u0020en\u0020el\u0020almacenamiento.",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Devuelve\u0020un\u0020usuario.",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020un\u0020usuario",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020en\u0020Base\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020usuario",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020en\u0020Base\u0020de\u0020datos\u0020el\u0020registro\u0020de\u0020la\u0020tabla\u0020usuario",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003A\u0024UsuarioModel",
            "name": "UsuarioModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-UsuarioController.html#property_UsuarioModel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController",
            "name": "VehiculoController",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003AgetByPlaca\u0028\u0029",
            "name": "getByPlaca",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_getByPlaca"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003A\u0024VehiculoModel",
            "name": "VehiculoModel",
            "summary": "",
            "url": "classes/App-Http-Controllers-VehiculoController.html#property_VehiculoModel"
        },                {
            "fqsen": "\\App\\Http\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Http-Kernel.html"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middleware",
            "name": "middleware",
            "summary": "The\u0020application\u0027s\u0020global\u0020HTTP\u0020middleware\u0020stack.",
            "url": "classes/App-Http-Kernel.html#property_middleware"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middlewareGroups",
            "name": "middlewareGroups",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware\u0020groups.",
            "url": "classes/App-Http-Kernel.html#property_middlewareGroups"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024routeMiddleware",
            "name": "routeMiddleware",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware.",
            "url": "classes/App-Http-Kernel.html#property_routeMiddleware"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate",
            "name": "Authenticate",
            "summary": "",
            "url": "classes/App-Http-Middleware-Authenticate.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate\u003A\u003AredirectTo\u0028\u0029",
            "name": "redirectTo",
            "summary": "Get\u0020the\u0020path\u0020the\u0020user\u0020should\u0020be\u0020redirected\u0020to\u0020when\u0020they\u0020are\u0020not\u0020authenticated.",
            "url": "classes/App-Http-Middleware-Authenticate.html#method_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies",
            "name": "EncryptCookies",
            "summary": "",
            "url": "classes/App-Http-Middleware-EncryptCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020cookies\u0020that\u0020should\u0020not\u0020be\u0020encrypted.",
            "url": "classes/App-Http-Middleware-EncryptCookies.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "name": "PreventRequestsDuringMaintenance",
            "summary": "",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020reachable\u0020while\u0020maintenance\u0020mode\u0020is\u0020enabled.",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated",
            "name": "RedirectIfAuthenticated",
            "summary": "",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings",
            "name": "TrimStrings",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrimStrings.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020attributes\u0020that\u0020should\u0020not\u0020be\u0020trimmed.",
            "url": "classes/App-Http-Middleware-TrimStrings.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts",
            "name": "TrustHosts",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustHosts.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts\u003A\u003Ahosts\u0028\u0029",
            "name": "hosts",
            "summary": "Get\u0020the\u0020host\u0020patterns\u0020that\u0020should\u0020be\u0020trusted.",
            "url": "classes/App-Http-Middleware-TrustHosts.html#method_hosts"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies",
            "name": "TrustProxies",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustProxies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024proxies",
            "name": "proxies",
            "summary": "The\u0020trusted\u0020proxies\u0020for\u0020this\u0020application.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_proxies"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "The\u0020headers\u0020that\u0020should\u0020be\u0020used\u0020to\u0020detect\u0020proxies.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_headers"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken",
            "name": "VerifyCsrfToken",
            "summary": "",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020excluded\u0020from\u0020CSRF\u0020verification.",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Requests\\CompraFormRequest",
            "name": "CompraFormRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-CompraFormRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\CompraFormRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-CompraFormRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\CompraFormRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-CompraFormRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Models\\Categoria",
            "name": "Categoria",
            "summary": "",
            "url": "classes/App-Models-Categoria.html"
        },                {
            "fqsen": "\\App\\Models\\Categoria\u003A\u003AgetListadoActivos\u0028\u0029",
            "name": "getListadoActivos",
            "summary": "",
            "url": "classes/App-Models-Categoria.html#method_getListadoActivos"
        },                {
            "fqsen": "\\App\\Models\\Categoria\u003A\u003AgetListadoActivoConTipoServicio\u0028\u0029",
            "name": "getListadoActivoConTipoServicio",
            "summary": "",
            "url": "classes/App-Models-Categoria.html#method_getListadoActivoConTipoServicio"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompra",
            "name": "DocumentoCompra",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompra.html"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompra\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompra.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompra\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompra.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompra\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompra.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompra\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompra.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompra\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompra.html#property_guarded"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompraDetalle",
            "name": "DocumentoCompraDetalle",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompraDetalle.html"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompraDetalle\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompraDetalle.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompraDetalle\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompraDetalle.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompraDetalle\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompraDetalle.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompraDetalle\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompraDetalle.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\DocumentoCompraDetalle\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/App-Models-DocumentoCompraDetalle.html#property_guarded"
        },                {
            "fqsen": "\\App\\Models\\Empresa",
            "name": "Empresa",
            "summary": "",
            "url": "classes/App-Models-Empresa.html"
        },                {
            "fqsen": "\\App\\Models\\Kardex",
            "name": "Kardex",
            "summary": "",
            "url": "classes/App-Models-Kardex.html"
        },                {
            "fqsen": "\\App\\Models\\LogAcceso",
            "name": "LogAcceso",
            "summary": "",
            "url": "classes/App-Models-LogAcceso.html"
        },                {
            "fqsen": "\\App\\Models\\LogAcceso\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-LogAcceso.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\OrdenAtencionDetalle",
            "name": "OrdenAtencionDetalle",
            "summary": "",
            "url": "classes/App-Models-OrdenAtencionDetalle.html"
        },                {
            "fqsen": "\\App\\Models\\OrdenesAtencion",
            "name": "OrdenesAtencion",
            "summary": "",
            "url": "classes/App-Models-OrdenesAtencion.html"
        },                {
            "fqsen": "\\App\\Models\\OrdenesAtencion\u003A\u003AgetListadoOrdenes\u0028\u0029",
            "name": "getListadoOrdenes",
            "summary": "",
            "url": "classes/App-Models-OrdenesAtencion.html#method_getListadoOrdenes"
        },                {
            "fqsen": "\\App\\Models\\OrdenesAtencion\u003A\u003AgetLastOrdenID\u0028\u0029",
            "name": "getLastOrdenID",
            "summary": "",
            "url": "classes/App-Models-OrdenesAtencion.html#method_getLastOrdenID"
        },                {
            "fqsen": "\\App\\Models\\OrdenesAtencion\u003A\u003AgenerarNumeroOrden\u0028\u0029",
            "name": "generarNumeroOrden",
            "summary": "",
            "url": "classes/App-Models-OrdenesAtencion.html#method_generarNumeroOrden"
        },                {
            "fqsen": "\\App\\Models\\OrdenesAtencion\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-OrdenesAtencion.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Producto",
            "name": "Producto",
            "summary": "",
            "url": "classes/App-Models-Producto.html"
        },                {
            "fqsen": "\\App\\Models\\Producto\u003A\u003AgetListadoActivos\u0028\u0029",
            "name": "getListadoActivos",
            "summary": "",
            "url": "classes/App-Models-Producto.html#method_getListadoActivos"
        },                {
            "fqsen": "\\App\\Models\\Producto\u003A\u003AgetListadoActivoConCategorias\u0028\u0029",
            "name": "getListadoActivoConCategorias",
            "summary": "",
            "url": "classes/App-Models-Producto.html#method_getListadoActivoConCategorias"
        },                {
            "fqsen": "\\App\\Models\\Sujeto",
            "name": "Sujeto",
            "summary": "",
            "url": "classes/App-Models-Sujeto.html"
        },                {
            "fqsen": "\\App\\Models\\Sujeto\u003A\u003AgetListadoClientes\u0028\u0029",
            "name": "getListadoClientes",
            "summary": "",
            "url": "classes/App-Models-Sujeto.html#method_getListadoClientes"
        },                {
            "fqsen": "\\App\\Models\\Sujeto\u003A\u003AgetListadoProveedores\u0028\u0029",
            "name": "getListadoProveedores",
            "summary": "",
            "url": "classes/App-Models-Sujeto.html#method_getListadoProveedores"
        },                {
            "fqsen": "\\App\\Models\\Sujeto\u003A\u003AgetProveedorByDNI\u0028\u0029",
            "name": "getProveedorByDNI",
            "summary": "",
            "url": "classes/App-Models-Sujeto.html#method_getProveedorByDNI"
        },                {
            "fqsen": "\\App\\Models\\Sujeto\u003A\u003AgetClienteByDNI\u0028\u0029",
            "name": "getClienteByDNI",
            "summary": "",
            "url": "classes/App-Models-Sujeto.html#method_getClienteByDNI"
        },                {
            "fqsen": "\\App\\Models\\TipoServicio",
            "name": "TipoServicio",
            "summary": "",
            "url": "classes/App-Models-TipoServicio.html"
        },                {
            "fqsen": "\\App\\Models\\TipoServicio\u003A\u003AgetListadoActivos\u0028\u0029",
            "name": "getListadoActivos",
            "summary": "",
            "url": "classes/App-Models-TipoServicio.html#method_getListadoActivos"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\App\\Models\\Usuario",
            "name": "Usuario",
            "summary": "",
            "url": "classes/App-Models-Usuario.html"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AgetListadoActivos\u0028\u0029",
            "name": "getListadoActivos",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_getListadoActivos"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AgetListadoPorRol\u0028\u0029",
            "name": "getListadoPorRol",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_getListadoPorRol"
        },                {
            "fqsen": "\\App\\Models\\Vehiculo",
            "name": "Vehiculo",
            "summary": "",
            "url": "classes/App-Models-Vehiculo.html"
        },                {
            "fqsen": "\\App\\Models\\Vehiculo\u003A\u003AgetListadoVehiculos\u0028\u0029",
            "name": "getListadoVehiculos",
            "summary": "",
            "url": "classes/App-Models-Vehiculo.html#method_getListadoVehiculos"
        },                {
            "fqsen": "\\App\\Models\\Vehiculo\u003A\u003AgetVehiculoByPlaca\u0028\u0029",
            "name": "getVehiculoByPlaca",
            "summary": "",
            "url": "classes/App-Models-Vehiculo.html#method_getVehiculoByPlaca"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider",
            "name": "AuthServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AuthServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020authentication\u0020\/\u0020authorization\u0020services.",
            "url": "classes/App-Providers-AuthServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003A\u0024policies",
            "name": "policies",
            "summary": "The\u0020policy\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-AuthServiceProvider.html#property_policies"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider",
            "name": "BroadcastServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-BroadcastServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-BroadcastServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider",
            "name": "EventServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-EventServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020events\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003AshouldDiscoverEvents\u0028\u0029",
            "name": "shouldDiscoverEvents",
            "summary": "Determine\u0020if\u0020events\u0020and\u0020listeners\u0020should\u0020be\u0020automatically\u0020discovered.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_shouldDiscoverEvents"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003A\u0024listen",
            "name": "listen",
            "summary": "The\u0020event\u0020listener\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#property_listen"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider",
            "name": "RouteServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-RouteServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Define\u0020your\u0020route\u0020model\u0020bindings,\u0020pattern\u0020filters,\u0020etc.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AconfigureRateLimiting\u0028\u0029",
            "name": "configureRateLimiting",
            "summary": "Configure\u0020the\u0020rate\u0020limiters\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_configureRateLimiting"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AHOME",
            "name": "HOME",
            "summary": "The\u0020path\u0020to\u0020the\u0020\u0022home\u0022\u0020route\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#constant_HOME"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory",
            "name": "UserFactory",
            "summary": "",
            "url": "classes/Database-Factories-UserFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UserFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Aunverified\u0028\u0029",
            "name": "unverified",
            "summary": "Indicate\u0020that\u0020the\u0020model\u0027s\u0020email\u0020address\u0020should\u0020be\u0020unverified.",
            "url": "classes/Database-Factories-UserFactory.html#method_unverified"
        },                {
            "fqsen": "\\Database\\Seeders\\CategoriasTableSeeder",
            "name": "CategoriasTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-CategoriasTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\CategoriasTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Corre\u0020insert\u0020en\u0020la\u0020tabla",
            "url": "classes/Database-Seeders-CategoriasTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\CategoriasTableSeeder\u003A\u003A\u0024categorias",
            "name": "categorias",
            "summary": "",
            "url": "classes/Database-Seeders-CategoriasTableSeeder.html#property_categorias"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Realiza\u0020el\u0020llamado\u0020de\u0020las\u0020siembras\u0020o\u0020inserciones\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\EmpresaTableSeeder",
            "name": "EmpresaTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-EmpresaTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\EmpresaTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Corre\u0020insert\u0020en\u0020la\u0020tabla",
            "url": "classes/Database-Seeders-EmpresaTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\EmpresaTableSeeder\u003A\u003A\u0024empresas",
            "name": "empresas",
            "summary": "",
            "url": "classes/Database-Seeders-EmpresaTableSeeder.html#property_empresas"
        },                {
            "fqsen": "\\Database\\Seeders\\SujetosTableSeeder",
            "name": "SujetosTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-SujetosTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\SujetosTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Corre\u0020insert\u0020en\u0020la\u0020tabla",
            "url": "classes/Database-Seeders-SujetosTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\SujetosTableSeeder\u003A\u003A\u0024Sujetos",
            "name": "Sujetos",
            "summary": "",
            "url": "classes/Database-Seeders-SujetosTableSeeder.html#property_Sujetos"
        },                {
            "fqsen": "\\Database\\Seeders\\TipoServiciosTableSeeder",
            "name": "TipoServiciosTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-TipoServiciosTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\TipoServiciosTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Corre\u0020insert\u0020en\u0020la\u0020tabla",
            "url": "classes/Database-Seeders-TipoServiciosTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\TipoServiciosTableSeeder\u003A\u003A\u0024TiposServicios",
            "name": "TiposServicios",
            "summary": "",
            "url": "classes/Database-Seeders-TipoServiciosTableSeeder.html#property_TiposServicios"
        },                {
            "fqsen": "\\Database\\Seeders\\UsuarioSeeder",
            "name": "UsuarioSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-UsuarioSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\UsuarioSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Corre\u0020insert\u0020en\u0020la\u0020tabla",
            "url": "classes/Database-Seeders-UsuarioSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\UsuarioSeeder\u003A\u003A\u0024Usuarios",
            "name": "Usuarios",
            "summary": "",
            "url": "classes/Database-Seeders-UsuarioSeeder.html#property_Usuarios"
        },                {
            "fqsen": "\\LARAVEL_START",
            "name": "LARAVEL_START",
            "summary": "",
            "url": "namespaces/default.html#constant_LARAVEL_START"
        },                {
            "fqsen": "\\Tests\\CreatesApplication",
            "name": "CreatesApplication",
            "summary": "",
            "url": "classes/Tests-CreatesApplication.html"
        },                {
            "fqsen": "\\Tests\\CreatesApplication\u003A\u003AcreateApplication\u0028\u0029",
            "name": "createApplication",
            "summary": "Creates\u0020the\u0020application.",
            "url": "classes/Tests-CreatesApplication.html#method_createApplication"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Feature-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest\u003A\u003Atest_the_application_returns_a_successful_response\u0028\u0029",
            "name": "test_the_application_returns_a_successful_response",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Feature-ExampleTest.html#method_test_the_application_returns_a_successful_response"
        },                {
            "fqsen": "\\Tests\\TestCase",
            "name": "TestCase",
            "summary": "",
            "url": "classes/Tests-TestCase.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Unit-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest\u003A\u003Atest_that_true_is_true\u0028\u0029",
            "name": "test_that_true_is_true",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Unit-ExampleTest.html#method_test_that_true_is_true"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/app-enums.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Http\\Requests",
            "name": "Requests",
            "summary": "",
            "url": "namespaces/app-http-requests.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        },                {
            "fqsen": "\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/tests.html"
        },                {
            "fqsen": "\\Tests\\Feature",
            "name": "Feature",
            "summary": "",
            "url": "namespaces/tests-feature.html"
        },                {
            "fqsen": "\\Tests\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "namespaces/tests-unit.html"
        }            ]
);
